import React, { useState, useRef } from 'react';
import { ContentBlock, ChartConfig } from '../types';
import { ChartRenderer } from './ChartRenderer';
import { motion } from 'framer-motion';
import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';
import { Button } from './Button';
import { detectDirection } from '../services/storageService';

interface ArticleViewProps {
  blocks: ContentBlock[];
  originalText?: string;
  onBack: () => void;
  onRegenerate: (text: string) => void;
  title?: string;
}

// Localization Dictionary
const UI_TEXT = {
  ltr: {
    back: "Back",
    enhanced: "Enhanced",
    original: "Original",
    regenerate: "Regenerate",
    exportPdf: "Export PDF",
    reportTag: "Report",
    generatedBy: "Generated by ChartGenius",
    chartInserted: "Chart inserted below"
  },
  rtl: {
    back: "بازگشت",
    enhanced: "پیشرفته",
    original: "متن اصلی",
    regenerate: "تولید مجدد",
    exportPdf: "دانلود PDF",
    reportTag: "گزارش",
    generatedBy: "تولید شده توسط ChartGenius",
    chartInserted: "نمودار در ادامه درج شده است"
  }
};

export const ArticleView: React.FC<ArticleViewProps> = ({ blocks: initialBlocks, originalText, onBack, onRegenerate, title = "Analysis Results" }) => {
  const [blocks, setBlocks] = useState(initialBlocks);
  const [viewMode, setViewMode] = useState<'enhanced' | 'original'>('enhanced');
  const [isExporting, setIsExporting] = useState(false);
  const articleRef = useRef<HTMLDivElement>(null);

  // Determine direction from original text (or default to LTR)
  const direction = originalText ? detectDirection(originalText) : 'ltr';
  const isRtl = direction === 'rtl';
  const ui = isRtl ? UI_TEXT.rtl : UI_TEXT.ltr;

  // Format Date based on locale
  const dateStr = new Date().toLocaleDateString(isRtl ? 'fa-IR' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const handleExportPDF = async () => {
    if (!articleRef.current) return;
    
    setIsExporting(true);
    try {
      const element = articleRef.current;
      
      // Use html-to-image (toPng) instead of html2canvas for better RTL/Font support
      const dataUrl = await toPng(element, { 
        cacheBust: true,
        backgroundColor: '#ffffff',
        pixelRatio: 2, // 2x resolution for good print quality
        style: {
           // Explicitly set font to ensure capture picks it up
           fontFamily: isRtl ? 'Vazirmatn, sans-serif' : 'Inter, sans-serif'
        },
        fetchRequestInit: {
            mode: 'cors'
        }
      });
      
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      
      // Load image to get dimensions
      const img = new Image();
      img.src = dataUrl;
      await new Promise((resolve) => { img.onload = resolve; });

      const pdfHeight = (img.height * pdfWidth) / img.width;
      const pageHeight = pdf.internal.pageSize.getHeight();
      
      let heightLeft = pdfHeight;
      let position = 0;

      // Add first page
      pdf.addImage(dataUrl, 'PNG', 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;

      // Add subsequent pages if content is long
      while (heightLeft >= 0) {
        position = heightLeft - pdfHeight;
        pdf.addPage();
        pdf.addImage(dataUrl, 'PNG', 0, position, pdfWidth, pdfHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`${title.replace(/\s+/g, '-').toLowerCase()}.pdf`);
    } catch (error) {
      console.error('Export failed', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const updateBlockColor = (blockId: string, newColor: string) => {
    setBlocks(prev => prev.map(b => {
        if (b.id === blockId && b.chartConfig) {
            return { ...b, chartConfig: { ...b.chartConfig, color: newColor } };
        }
        return b;
    }));
  };

  const handleRemoveBlock = (blockId: string) => {
    if (confirm("Are you sure you want to remove this chart?")) {
        setBlocks(prev => prev.filter(b => b.id !== blockId));
    }
  };

  const displayBlocks = viewMode === 'original' 
    ? blocks.filter(b => b.type === 'text') 
    : blocks;

  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto">
      {/* Toolbar */}
      <div className={`sticky top-0 z-30 mb-8 bg-white/90 backdrop-blur-md p-4 rounded-xl border border-slate-200 shadow-sm flex flex-wrap items-center justify-between gap-4 transition-all ${isRtl ? 'font-persian' : 'font-sans'}`}>
         <div className="flex items-center gap-3">
            <button 
                onClick={onBack}
                className="p-2 rounded-lg text-slate-500 hover:text-slate-800 hover:bg-slate-100 transition-colors flex items-center gap-2 text-sm font-medium"
            >
                <svg className={`w-5 h-5 ${isRtl ? 'transform rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                {ui.back}
            </button>
            <div className="h-6 w-px bg-slate-200"></div>
            <div className="flex bg-slate-100 p-1 rounded-lg">
                <button 
                    onClick={() => setViewMode('enhanced')}
                    className={`px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded-md transition-all ${viewMode === 'enhanced' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    {ui.enhanced}
                </button>
                <button 
                    onClick={() => setViewMode('original')}
                    className={`px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded-md transition-all ${viewMode === 'original' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    {ui.original}
                </button>
            </div>
         </div>

        <div className="flex gap-2">
             {originalText && (
                <button 
                    onClick={() => onRegenerate(originalText)}
                    className="flex items-center text-sm px-3 py-2 rounded-lg text-slate-600 hover:bg-slate-100 transition-colors"
                >
                    <svg className="w-4 h-4 mx-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                    {ui.regenerate}
                </button>
            )}
            <Button 
                onClick={handleExportPDF}
                isLoading={isExporting}
                variant="primary"
                className="py-2 px-4 text-sm font-sans" 
                // Note: keeping PDF export button font sans for icon alignment unless we want strictly persian everywhere. 
                // But the parent div enforces font-persian, so this inner text will inherit.
                icon={
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                }
            >
                {ui.exportPdf}
            </Button>
        </div>
      </div>

      <article 
        ref={articleRef} 
        id="article-content" 
        className={`bg-white rounded-xl shadow-xl shadow-slate-200/50 overflow-hidden min-h-[80vh] border border-slate-100 ${isRtl ? 'font-persian' : 'font-serif'}`}
        dir={direction}
      >
        <div className="h-2 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"></div>
        <div className="p-8 md:p-12 lg:p-16">
          <header className="mb-10 border-b border-slate-100 pb-8">
            <span className={`inline-block px-3 py-1 bg-indigo-50 text-indigo-600 rounded-full text-xs font-bold tracking-wider uppercase mb-4 ${isRtl ? 'font-persian' : 'font-sans'}`}>
              {ui.reportTag}
            </span>
            <h1 className="text-3xl md:text-4xl font-bold text-slate-900 leading-tight">
              {title}
            </h1>
            <p className="mt-4 text-slate-500 text-sm flex gap-2">
               <span>{ui.generatedBy}</span>
               <span>·</span>
               <span dir="ltr">{dateStr}</span>
            </p>
          </header>

          <div className={`prose prose-lg prose-slate max-w-none prose-p:leading-relaxed prose-p:text-slate-600 ${isRtl ? 'prose-headings:font-persian' : 'prose-headings:font-serif'}`}>
            {displayBlocks.map((block, index) => {
                const nextBlockIsChart = blocks[index + 1]?.type === 'chart';
                
                return (
                  <motion.div
                    key={block.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                  >
                    {block.type === 'text' && block.content && (
                      <div className="mb-6 whitespace-pre-wrap relative">
                        {block.content}
                        {nextBlockIsChart && viewMode === 'enhanced' && (
                             <span 
                                className={`inline-flex items-center justify-center w-5 h-5 rounded-full bg-indigo-100 text-indigo-600 text-[10px] align-middle transform ${isRtl ? 'mr-2 translate-x-0' : 'ml-2 translate-x-1'}`} 
                                title={ui.chartInserted}
                             >
                                📊
                             </span>
                        )}
                      </div>
                    )}
                    {block.type === 'chart' && block.chartConfig && (
                       <div className={`my-12 ${isRtl ? 'pr-4 border-r-4' : 'pl-4 border-l-4'} border-indigo-500/30`}>
                           <ChartRenderer 
                                config={block.chartConfig} 
                                onColorChange={(color) => updateBlockColor(block.id, color)}
                                onRemove={() => handleRemoveBlock(block.id)}
                                isRtl={isRtl}
                            />
                       </div>
                    )}
                  </motion.div>
                );
            })}
          </div>
        </div>
      </article>
    </div>
  );
};