import React, { useEffect } from 'react';
import { motion } from 'framer-motion';

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-white font-sans text-slate-900 selection:bg-indigo-100 selection:text-indigo-700">
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-100">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
           <div className="flex items-center gap-2 cursor-pointer" onClick={onBack}>
              <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center text-white">
                 <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
                    <path fillRule="evenodd" clipRule="evenodd" d="M5 14C5 12.8954 5.89543 12 7 12H9C10.1046 12 11 12.8954 11 14V21H7C5.89543 21 5 20.1046 5 19V14Z" fillOpacity="0.7" />
                    <path fillRule="evenodd" clipRule="evenodd" d="M13 7C13 5.89543 13.8954 5 15 5H17C18.1046 5 19 5.89543 19 7V21H15C13.8954 21 13 20.1046 13 19V7Z" />
                 </svg>
              </div>
              <span className="font-bold text-xl tracking-tight">ChartGenius</span>
           </div>
           <button 
             onClick={onBack} 
             className="text-sm font-medium text-slate-500 hover:text-indigo-600 transition-colors px-4 py-2 rounded-lg hover:bg-slate-50"
           >
             Close
           </button>
        </div>
      </nav>
      
      <main className="max-w-3xl mx-auto px-6 py-16">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <h1 className="text-4xl md:text-5xl font-extrabold mb-10 text-slate-900 tracking-tight">Terms of Service</h1>
          
          <div className="prose prose-slate prose-lg max-w-none prose-headings:font-bold prose-a:text-indigo-600">
             <p className="lead text-xl text-slate-500 mb-8 border-b border-slate-100 pb-8">
              Effective Date: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>

            <h3>1. Acceptance of Terms</h3>
            <p>
              By accessing or using ChartGenius ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>

            <h3>2. Description of Service</h3>
            <p>
              ChartGenius is an AI-powered tool that analyzes text input to generate data visualizations. The Service is provided "as is" and "as available." We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
            </p>

            <h3>3. User Conduct</h3>
            <p>You agree not to use the Service to:</p>
            <ul>
                <li>Process text that includes illegal, hate speech, or sexually explicit content.</li>
                <li>Violate any applicable local, state, national, or international law.</li>
                <li>Attempt to reverse engineer, decompile, or hack the Service.</li>
                <li>Input sensitive Personal Identifiable Information (PII) such as credit card numbers or social security numbers.</li>
            </ul>

            <h3>4. Intellectual Property Rights</h3>
            <p>
                <strong>Your Content:</strong> You retain all rights to the text you input and the reports generated. By using the Service, you grant us a license to process this content solely for the purpose of providing the Service to you.
            </p>
            <p>
                <strong>Our Content:</strong> The ChartGenius interface, code, graphics, and design are owned by us and protected by copyright and other intellectual property laws.
            </p>

            <h3>5. Disclaimer of Warranties</h3>
            <p>
                The Service relies on Artificial Intelligence to generate insights. AI can occasionally produce incorrect or misleading information ("hallucinations"). <strong>You are responsible for verifying the accuracy of any charts or data generated by the Service before relying on them.</strong> We do not warrant that the results will be accurate, complete, or reliable.
            </p>

            <h3>6. Limitation of Liability</h3>
            <p>
                In no event shall ChartGenius be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of the Service.
            </p>

            <h3>7. Governing Law</h3>
            <p>
                These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
            </p>
            
            <h3>8. Changes to Terms</h3>
            <p>
                We reserve the right to modify these terms at any time. We will provide notice of significant changes by updating the date at the top of this policy.
            </p>
          </div>
        </motion.div>
      </main>
    </div>
  );
};